version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run: yarn global add now
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn dev-build
      - run: cd dist && $HOME/.config/yarn/global/node_modules/.bin/now -t ${NOW_TOKEN} && $HOME/.config/yarn/global/node_modules/.bin/now alias -t ${NOW_TOKEN}
